version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  worker:
    build: ./machine-learning-client
    container_name: worker
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=ml_system
    restart: always
  web-app:
    build: ./web-app
    container_name: web-app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    ports:
      - "5001:5000"
    restart: always

volumes:
  mongo_data:
